### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by gallardoandres18** [vlafranca/ngxAutocomPlace#3]
![image](https://user-images.githubusercontent.com/10620758/86256108-4a07d980-bb8e-11ea-8e9f-85585f7fb15d.png)
![image](https://user-images.githubusercontent.com/10620758/86256130-52601480-bb8e-11ea-997f-678e0f3fc04b.png)

I want that only displays places and address that are of Argentina. Are you telling me what i'm doing wrong?

Sorry for my little english :(.

Thanks

**Comment by vlafranca** [comment]
Hi @gallardoandres18, indeed there is a bug on this side. I will release a new version soon to fix this.

Thanks for report.

**Comment by vlafranca** [comment]
Resolved in version 0.8.2.
