### ISSUE TITLE
Cannot read properties of undefined (reading 'classList')

### ISSUE THREAD

**Issue by balinenidileep** [vlafranca/ngxAutocomPlace#33]
Hi, I am using the ngxAutocomPlace library for autocomplete street addresses, Here when I am using the down keyword which is trowing **the Cannot read properties of undefined (reading 'classList')** error ,after selecting the street address
 Is there any way to avoid the issue? 
`error-logging.service.ts:16 TypeError: Cannot read properties of undefined (reading 'classList')
    at NgxAutocomPlaceDirective.keydownEvent (:4200/vendor.js:171342:80)
    at HTMLInputElement.<anonymous> (:4200/vendor.js:171259:22)
    at ZoneDelegate.invokeTask (:4200/polyfills.js:11022:31)
    at Object.onInvokeTask (:4200/vendor.js:56311:33)
    at ZoneDelegate.invokeTask (:4200/polyfills.js:11021:60)
    at Zone.runTask (:4200/polyfills.js:10794:47)
    at ZoneTask.invokeTask [as invoke] (:4200/polyfills.js:11103:34)
    at invokeTask (:4200/polyfills.js:12216:14)
    at HTMLInputElement.globalZoneAwareCallback (:4200/polyfills.js:12242:17)`

**Comment by vlafranca** [comment]
Hi @balinenidileep , are you able to provide a playground on stackblitz or codepen where we can reproduce this error ?
Also what do you mean by "down keyword" ?

Thanks

**Comment by balinenidileep** [comment]
Hi @vlafranca  here down keyword means down arrow (<html>
<body>


↓ | Downwards Arrow | 25
-- | -- | --



</body>
</html>

Sorry I am unable to provide the playground on stackblitz due to authkey limitation

**Comment by balinenidileep** [comment]
@vlafranca  here the playground above issue 
https://stackblitz.com/edit/ngx-google-places-autocomplete-j1bbch?file=src%2Fapp%2Fapp.component.html

**Comment by balinenidileep** [comment]
@all is anyone have this kind of issue

**Comment by vlafranca** [comment]
@balinenidileep have you set your google api key correctly ?

**Comment by balinenidileep** [comment]
> ave you set your google api key correc

Yes @vlafranca  google API key was correctly added and I am able to fetch the details , This issue I am seeing is when a user does not enter any characters in the input box then used down arrow key this issue able reproduce

**Comment by vlafranca** [comment]
@balinenidileep thanks for finally providing accurate reproduction steps.
Fixing it.

**Comment by vlafranca** [comment]
Fixed in version 4.0.1
